---
driver:
  name: vagrant
  vagrantfile_erb: ".Vagrantfile.erb"
provisioner:
  name: chef_solo
  require_chef_omnibus: 12.9.38
  chef_omnibus_install_options: "-d /tmp/vagrant-cache/vagrant_omnibus"
verifier:
  name: inspec
  format: documentation
platforms:
  - name: debian-8.3
suites:
- name: airplay
  run_list:
  - recipe[chip-audio::airplay]
  attributes:
