AllCops:
  Include:
  - Berksfile
  - Gemfile
  - Rakefile
  Exclude:
  - vendor/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
Style/SpaceBeforeFirstArg:
  Enabled: false
StringLiterals:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
