name              'chip-audio'
maintainer        'wschiffels'
maintainer_email  'wschiffels@users.noreply.github.com'
license           'Apache 2.0'
issues_url        'https://github.com/wschiffels/chip-audio/issues'
source_url        'https://github.com/wschiffels/chip-audio/'
description       'Installs/configures audio bridges on a chip'
version           '0.1.0'
recipe            'chip-audio::airplay', 'Installs/configures airplay for chip'
supports          'debian'
