Vagrant.configure("2") do |c|
  c.vm.box = "bento/debian-8.3"
  c.vm.box_url = ""
  if Vagrant.has_plugin?("vagrant-cachier")
    c.cache.auto_detect = true
    c.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-omnibus")
    c.omnibus.cache_packages = true
    c.omnibus.chef_version = ""
  end
  c.vm.hostname = "airplay-debian-83"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
